### ISSUE TITLE
codesign will not work for libs installed later.

### ISSUE THREAD

**Issue by AliasT** [gregneagle/relocatable-python#15]
https://github.com/gregneagle/relocatable-python/blob/main/make_relocatable_python_framework.py#L85-L95

maybe move codesign after pip.

**Comment by gregneagle** [comment]
Have you actually observed an issue this code causes?

I think you might be misunderstanding what is actually happening here.

The process of making the Python framework relocatable makes changes to the complied binary libraries. Such changes break code signing. Originally that was not an issue because the official python.org Python framework prior to about 3.8 was not signed.

At some point, python.org started signing the framework. This caused the relocatable changes to break code signing. This in itself wasn't actually a big functional problem, but some security tools understandably flagged the framework as suspicious/problematic.

So the original "fix" was to simply strip code signing altogether. Better to have no code signing than broken code signing. And this worked fine until we needed to make a Universal2 build. Apple silicon will not execute unsigned arm64 code at all. It has to have at least an ad-hoc signature. So instead of stripping code signatures, now we re-sign the affected binaries with an ad-hoc signature. Without this, Apple silicon will refuse to run the code.

What about things installed later via pip? These are not modified by the "relocatablizer". If they are broken from a code-signing point of view, then they'd be broken when installed against any other Python install as well, and aren't really the responsibility of my script to fix.

If there are issues here, I'd be interested in the details, but most likely the correct fix is outside of my script.

**Comment by AliasT** [comment]
Currently we are embeding `relocatable python` into an electron app，include all the libs installed later. apple complains about packaging.
So, we are codesign third parties manually. Thanks for the reply.
